### ISSUE TITLE
CSNumerics Bobyqa error

### ISSUE THREAD

**Issue by arch-tu** [AlanRynne/Geodesic-Patterns#1]
Hi Rynne,

Thanks for your work. It's great!

when I tested your scripts in Windows, it always showed that the function of Bobyqa is wrong. I used CSNumerics.dll -1.0.1.50806.

which version of CSNumerics you used? Or is it possible shared the .gha file?

Best regards

**Comment by AlanRynne** [comment]
Hi!! Thanks for taking the time to report this. This was the code for my masters dissertation a couple of years back and I developed it in less than 3 months so it is quite a mess...😅
I’ll try to find a while during this weekend to find my compiled version with all the dll or try to point you to a commit that would work!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arch-tu** [comment]
Hi Rynne,

Thank you for your reply!

Acturally, I don't know how to use the function of "Compute" in the class "GeodesicsFromLevelSets" from "MeshGeodesicMethods". In your code, the input contain two parameters "int i"&"double[] x",however, the parameter "int i" doesn't be used in the function.

Then, in the "LevelSetGeodesicsComponent",
'var optimizer = new  Bobyqa(mesh.Vertices.Count, levelSets.Compute);'
it does't work,
<img width="390" alt="WeChat Image_20200301105844" src="https://user-images.githubusercontent.com/29678019/75616933-a8568880-5bab-11ea-8e0b-a4e70e394792.png">
the Bobyqa needs 4 input parameter, in your code ,only ofter two parameters.

Sorry to bother you!

**Comment by AlanRynne** [comment]
I’m guessing you are using the csnumerics nugget package? If so, don’t.😅 I suggest you download the csnumerics project from GitHub, add it to this project solution and replace the csnumerics reference with the project reference. That should get it to build. I checked this last night and it builds for me, but please tell me if you have any trouble!

The problem is that csnumerics is an abandoned project that was las updated 3 years ago. And the nuget package is older than the version in GitHub.

Hope it helps!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlanRynne** [comment]
Also....the geodesicsFromLevelSets method is the last one I managed to program and the optimization is NOT optimal (although that might sound counter intuitive). Basically, I’m using gradient less optimization for this,but the paper does this analytically, meaning my method is unstable and SLOW☹️ the paralleltransport and piecewise geodesic are more stable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlanRynne** [comment]
I made the changes I suggested for you in PR #3. You would just need to download the csnumerics project somewhere on your computer and relink it to the solution. I also changed the Grasshopper references to a nuget package (works with latest version of rhino in mac, and i guess in windows too). Everything else should compile 😄 
Pull the changes in the master branch and tell me how it goes! 👍
By the way, thanks for the interest! It's always nice to know somebody is finding my work useful.

EDIT: I just added a release with the compiled .gha plus al necessary dll's in case you want to try it without playing with the code 😉. You'll find it [HERE](https://github.com/AlanRynne/Geodesic-Patterns/releases/tag/v1.0-beta.1)

**Comment by arch-tu** [comment]
Hi ,Rynne!

Thank you for your help!
I think your work is important to architects and I like it. Geodesic plays an important role in Architectural Geometry. I am learning it and glad to see your works. It is a great help to me.
I will test the new project as soon as  possible.
 Thanks again!

**Comment by AlanRynne** [comment]
Since I haven't heard back from you @arch-tu, I'm assuming you got it all working! I'm closing this issue but feel free to re-open it or create a new one if you have further trouble!

**Comment by arch-tu** [comment]
Sorry for my late reply.

I had to do other works during these days. Yes, I tested the ParallelTransport and BestFit methods using native C# component in Grasshopper. They are working well and enough to me. I will test the geodesicsFromLevelSets method when I have a free time.

Thank you for all your help!
