### ISSUE TITLE
Is "BothDir" wrong in the BestFit-PieceWise Method?

### ISSUE THREAD

**Issue by arch-tu** [AlanRynne/Geodesic-Patterns#4]
Hi, Alan，

Recently, I tested the BestFit-piecewise Method again. I found the "BothDir" parameter isn‘t right. No matter what you set "true" or "false", it always give the same direction result. Furthermore, when I tried to Debug in the C# component, set the opposite start direction. It raises the error "1. Solution exception:index must be less than the size of the collection". Then I tested the same component from the MeshGeodesic .gha , it has the same problem.

Could you help me find the answer here？

Thanks

**Comment by AlanRynne** [comment]
Hi! 

Weird... basically what `bothDir` should be doing is just create 2 separate geodesics, one in the direction and one in its opposite; and finally join them to get just one curve as an output. So, I’m not quite sure why that would be happening. I’ll have a look along the week and get back to you!👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arch-tu** [comment]
Hi!

In my test,  when set the bothdir to true, there is something wrong with the function `GeneratePiecewiseGeodesicCurve`. It's strange. In my case, ` 
// Replace first parameter with the parameter of the piecewise curve endpoint at the perpGeod.
    var events = Intersection.CurveCurve(geodsAtEnd[0], bestFitG.selectedGeodesic, 0.0, 0.0);` 
The `events` is none. It means that the` geodsAtEnd` and` bestFitG.selectedGeodesic` doesn't intersect. Then I change the ` intersection_tolerance` from 0.0 to 0.1, it still doesn't work.
I hope this help and look forwad to your reply.
Thanks,

**Comment by arch-tu** [comment]
Hi!
In the BestFit-piecewise component, `bothdir` works as shown below.

<img width="169" alt="false" src="https://user-images.githubusercontent.com/29678019/81402086-156e3780-9174-11ea-85e3-f2d34b2f1c4c.png">This result of `bothdir=false` 

<img width="179" alt="true" src="https://user-images.githubusercontent.com/29678019/81402114-2323bd00-9174-11ea-9cf2-daabab887419.png">This result of `bothdir=true`

**Comment by AlanRynne** [comment]
Just writing to let you know I have not had time to check this, but it has not slipped my mind! I'll try to do it during this week 👍
